{
    'name': 'ACPEC FuelToken Core',
    'version': '1.0.3',
    'category': 'ACPEC/FuelToken',
    'summary': 'Cœur FuelToken : carnets, tickets, comptes, QR, stations et transactions',
    'author': 'ACPEC SARL',
    'website': 'https://acpec.odoorim.com',
    'license': 'OPL-1',
    'depends': ['acpec_fueltoken_purchase'],
    'data': [
        'security/ir.model.access.csv',
        'security/fueltoken_core_rules.xml',
        'data/ir_cron_data.xml',
        'data/purchase_line_snapshot_repair_m21e.xml',
        'data/ir_sequence_ticket_transfer_data.xml',
        'views/fuel_wallet_views.xml',
        'views/fuel_face_line_views.xml',
        'views/fuel_qr_views.xml',
        'views/fuel_station_views.xml',
        'views/fuel_station_agent_assignment_views.xml',
        'views/fuel_transaction_views.xml',
        'views/fuel_carnet_transfer_views.xml',
    ],
    'installable': True,
}
