API_CATALOG_FUELTOKEN = [
    {
        'group': 'FuelToken Mobile',
        'label': 'Lister les types de carnets',
        'route': '/api/acpec/fueltoken/v1/mobile/carnet-types',
        'method': 'POST',
        'payload': {},
        'requires_token': True,
        'note': "Retourne les types de carnets actifs disponibles pour la société de l’utilisateur mobile.",
    },
    {
        'group': 'FuelToken Mobile',
        'label': 'Wallet courant',
        'route': '/api/acpec/fueltoken/v1/mobile/wallet/current',
        'method': 'POST',
        'payload': {},
        'requires_token': True,
        'note': 'Retourne ou crée automatiquement le wallet du partenaire lié à l’utilisateur mobile connecté.',
    },
    {
        'group': 'FuelToken Mobile',
        'label': 'Créer une commande de carnets',
        'route': '/api/acpec/fueltoken/v1/mobile/purchases/create',
        'method': 'POST',
        'payload': {
            'lines': [{'carnet_type_id': 1, 'carnet_qty': 1}],
            'proof_filename': 'preuve_paiement_test.txt',
            'proof_data': 'UHJldXZlIGRlIHBhaWVtZW50IHRlc3Q=',
            'payment_reference': 'TEST-PAIEMENT-001',
            'idempotency_key': 'TEST-PURCHASE-001',
        },
        'requires_token': True,
        'note': 'Après création, la commande est soumise. Elle doit être validée dans le backend pour générer les faces disponibles.',
    },
    {
        'group': 'FuelToken Mobile',
        'label': 'Lister mes commandes de carnets',
        'route': '/api/acpec/fueltoken/v1/mobile/purchases',
        'method': 'POST',
        'payload': {},
        'requires_token': True,
        'note': 'Liste les commandes de carnets du client connecté.',
    },
    {
        'group': 'FuelToken Mobile',
        'label': 'Détail commande de carnets',
        'route': '/api/acpec/fueltoken/v1/mobile/purchases/detail',
        'method': 'POST',
        'payload': {'purchase_id': 1},
        'requires_token': True,
        'note': 'Retourne le détail de la commande : lignes, preuves, statut, dates et motif de rejet.',
    },
    {
        'group': 'FuelToken Mobile',
        'label': 'Historique transactions',
        'route': '/api/acpec/fueltoken/v1/mobile/transactions',
        'method': 'POST',
        'payload': {
            'date_from': '2026-01-01 00:00:00',
            'date_to': '2026-12-31 23:59:59',
            'limit': 20,
            'offset': 0,
        },
        'requires_token': True,
        'note': 'Liste paginée des transactions du wallet courant. Tous les filtres sont optionnels.',
    },
    {
        'group': 'FuelToken Mobile',
        'label': 'Détail transaction',
        'route': '/api/acpec/fueltoken/v1/mobile/transactions/detail',
        'method': 'POST',
        'payload': {'transaction_id': 1},
        'requires_token': True,
        'note': 'Retourne les lignes détaillées de la transaction.',
    },
    {
        'group': 'FuelToken Mobile',
        'label': 'Lister les faces disponibles',
        'route': '/api/acpec/fueltoken/v1/mobile/faces',
        'method': 'POST',
        'payload': {},
        'requires_token': True,
        'note': 'Affiche les lignes de faces disponibles après validation backend d’une commande.',
    },
    {
        'group': 'FuelToken Mobile',
        'route': '/api/acpec/fueltoken/v1/mobile/carnets/transfer',
        'label': 'Transferer des carnets',
        'method': 'POST',
        'payload': {
            'recipient_phone': 'REMPLACER-PAR-LOGIN-OU-TELEPHONE',
            'lines': [{'face_line_id': 1, 'carnet_qty': 1}],
            'note': 'Transfert test depuis la console API',
            'idempotency_key': 'TEST-CARNET-TRANSFER-001',
        },
        'requires_token': True,
        'note': 'Teste le transfert de carnets complets. Utiliser un face_line_id retourne par "Lister les faces disponibles" et le login/telephone du destinataire.',
    },
    {
        'group': 'FuelToken Mobile',
        'label': 'Historique des transferts',
        'route': '/api/acpec/fueltoken/v1/mobile/carnets/transfers',
        'method': 'POST',
        'payload': {
            'direction': 'sent',
            'limit': 20,
            'offset': 0,
        },
        'requires_token': True,
        'note': "Liste les transferts du client connecte. direction peut valoir 'sent', 'received' ou etre retiree pour tout afficher.",
    },
    {
        'group': 'FuelToken Mobile',
        'label': 'Émettre un QR',
        'route': '/api/acpec/fueltoken/v1/mobile/qr/issue',
        'method': 'POST',
        'payload': {
            'lines': [{'carnet_type_id': 1, 'qty': 1}],
            'idempotency_key': 'TEST-QR-ISSUE-001',
        },
        'requires_token': True,
        'note': 'Émet un QR depuis les faces disponibles du wallet. carnet_type_id est recommandé.',
    },
    {
        'group': 'FuelToken Mobile',
        'label': 'Lister mes QR',
        'route': '/api/acpec/fueltoken/v1/mobile/qr/list',
        'method': 'POST',
        'payload': {'state': 'active'},
        'requires_token': True,
        'note': 'Le champ state est optionnel : active, blocked, split, consumed, expired.',
    },
    {
        'group': 'FuelToken Mobile',
        'label': 'Détail d’un QR',
        'route': '/api/acpec/fueltoken/v1/mobile/qr/detail',
        'method': 'POST',
        'payload': {'public_code': 'QR-REMPLACER-PAR-CODE-REEL'},
        'requires_token': True,
        'note': 'Remplacer public_code par le code retourné par l’émission ou la liste des QR.',
    },
    {
        'group': 'FuelToken Mobile',
        'route': '/api/acpec/fueltoken/v1/mobile/qr/retirer',
        'label': 'Retirer des tickets d un QR',
        'method': 'POST',
        'payload': {
            'public_code': 'QR-REMPLACER-PAR-CODE-REEL',
            'lines': [{'qr_line_id': 1, 'qty': 1}],
            'idempotency_key': 'TEST-QR-RETIRER-001',
        },
        'requires_token': True,
        'note': 'Retire certaines lignes actives du QR source vers un nouveau QR. Utiliser qr_line_id depuis le detail QR.',
    },
    {
        'group': 'FuelToken Mobile',
        'route': '/api/acpec/fueltoken/v1/mobile/qr/separer',
        'label': 'Separer QR expire/non expire',
        'method': 'POST',
        'payload': {
            'public_code': 'QR-REMPLACER-PAR-CODE-REEL',
            'idempotency_key': 'TEST-QR-SEPARER-001',
        },
        'requires_token': True,
        'note': 'Separe automatiquement les lignes non expirees d un QR bloque/partiellement expire vers un nouveau QR actif.',
    },
    {
        'group': 'FuelToken Mobile',
        'label': 'Splitter un QR',
        'route': '/api/acpec/fueltoken/v1/mobile/qr/split',
        'method': 'POST',
        'payload': {
            'public_code': 'QR-REMPLACER-PAR-CODE-REEL',
            'children': [
                {'lines': [{'face_value': 500, 'qty': 1}]},
                {'lines': [{'face_value': 500, 'qty': 1}]},
            ],
            'idempotency_key': 'TEST-QR-SPLIT-001',
        },
        'requires_token': True,
        'note': 'Le split redistribue exactement les faces entières du QR parent.',
    },
    {
        'group': 'FuelToken Station',
        'label': 'Profil station',
        'route': '/api/acpec/fueltoken/v1/station/profile',
        'method': 'POST',
        'payload': {},
        'requires_token': True,
        'note': 'Nécessite un utilisateur station lié à acpec.fuel.station.',
    },
    {
        'group': 'FuelToken Station',
        'label': 'Vérifier un QR station',
        'route': '/api/acpec/fueltoken/v1/station/qr/check',
        'method': 'POST',
        'payload': {'public_code': 'QR-REMPLACER-PAR-CODE-REEL'},
        'requires_token': True,
        'note': 'Vérifie le QR sans le consommer.',
    },
    {
        'group': 'FuelToken Station',
        'label': 'Consommer un QR en station',
        'route': '/api/acpec/fueltoken/v1/station/qr/use',
        'method': 'POST',
        'payload': {
            'public_code': 'QR-REMPLACER-PAR-CODE-REEL',
            'idempotency_key': 'TEST-STATION-USE-001',
        },
        'requires_token': True,
        'note': 'Consomme définitivement un QR actif.',
    },
    {
        'group': 'FuelToken Station',
        'label': 'Transactions station',
        'route': '/api/acpec/fueltoken/v1/station/transactions',
        'method': 'POST',
        'payload': {'limit': 20, 'offset': 0},
        'requires_token': True,
        'note': 'Historique des consommations de la station connectée.',
    },
    {
        'group': 'FuelToken Admin',
        'label': 'Types de carnets',
        'route': '/api/acpec/fueltoken/v1/admin/carnet-types/list',
        'method': 'POST',
        'payload': {},
        'requires_token': True,
        'note': 'Nécessite un token manager/admin.',
    },
    {
        'group': 'FuelToken Admin',
        'label': 'Achats en attente',
        'route': '/api/acpec/fueltoken/v1/admin/purchases/pending',
        'method': 'POST',
        'payload': {'state': 'submitted'},
        'requires_token': True,
        'note': 'Liste les lots d’achat à valider.',
    },
    {
        'group': 'FuelToken Admin',
        'label': 'Valider achat',
        'route': '/api/acpec/fueltoken/v1/admin/purchases/approve',
        'method': 'POST',
        'payload': {'purchase_id': 1},
        'requires_token': True,
        'note': 'Valide le lot et déclenche la création des faces.',
    },
    {
        'group': 'FuelToken Admin',
        'label': 'Rejeter achat',
        'route': '/api/acpec/fueltoken/v1/admin/purchases/reject',
        'method': 'POST',
        'payload': {'purchase_id': 1, 'rejection_reason': 'Preuve non conforme.'},
        'requires_token': True,
        'note': 'Rejette le lot avec motif.',
    },
    {
        'group': 'FuelToken Admin',
        'label': 'Stations',
        'route': '/api/acpec/fueltoken/v1/admin/stations/list',
        'method': 'POST',
        'payload': {},
        'requires_token': True,
        'note': 'Liste les stations.',
    },
    {
        'group': 'FuelToken Admin',
        'label': 'Dashboard summary',
        'route': '/api/acpec/fueltoken/v1/admin/reports/summary',
        'method': 'POST',
        'payload': {},
        'requires_token': True,
        'note': 'Résumé global pour l’espace admin mobile.',
    },
]
