{'name': 'ACPEC Mobile Auth',
 'version': '19.0.1.18.2',
 'summary': 'Mobile account creation, approval, token sessions and app version policy',
 'description': 'Authentication and mobile identity backend for ACPEC mobile applications.',
 'category': 'Tools',
 'author': 'ACPEC SARL',
 'website': 'https://acpec.odoorim.com',
 'license': 'OPL-1',
 'depends': ['base', 'mail', 'portal'],
 'data': ['security/mobile_auth_groups.xml',
          'security/ir.model.access.csv',
          'data/ir_sequence_data.xml',
          'views/mobile_device_trust_wizard_views.xml',
          'views/mobile_auth_views.xml',
          'views/res_company_views.xml',
          'views/mobile_security_audit_log_views.xml',
          'views/mobile_auth_menu_views.xml',
          'views/mobile_security_setting_views.xml'],
 'application': True,
 'installable': True}
