[options]
admin_passwd = $pbkdf2-sha512$600000$YEwJISRECKEU4nzPea8VIg$0ACdT3BEbC5jUIVCty7k7oTeiA5RVN8Qs/DWG/6d5V/dXkgwV.UNtn3jmYs4fI57Xr4HaqYmuX5uLj3DYqCxxg
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = odoo
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
http_port = 8069
gevent_port = 8072
http_interface = 0.0.0.0
without_demo = True
