[options]
admin_passwd = CHANGE_ME
db_host = postgres16_svc
db_port = 5432
db_user = postgres16_odoo
db_password = CHANGE_ME
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/var/lib/odoo/addons/19.0,/mnt/extra-addons/github/enterprise-19.0,/mnt/extra-addons/github/FuelToken/FuelToken_Backend/addons
