API_CATALOG_MOBILE_AUTH = [
    {
        'group': 'Mobile Auth',
        'label': 'Version check',
        'route': '/api/acpec/mobile_auth/v1/version-check',
        'method': 'POST',
        'payload': {
            'platform': 'android',
            'app_version': '1.0.0',
            'build_number': 100,
        },
        'note': 'Endpoint public. Ne nécessite pas de token.',
    },
    {
        'group': 'Mobile Auth',
        'label': 'Signup companies',
        'route': '/api/acpec/mobile_auth/v1/signup-companies',
        'method': 'POST',
        'payload': {},
        'note': 'Endpoint public. Retourne les sociétés ouvertes à l’inscription mobile.',
    },
    {
        'group': 'Mobile Auth',
        'label': 'Signup',
        'route': '/api/acpec/mobile_auth/v1/signup',
        'method': 'POST',
        'payload': {
            'name': 'Client Test',
            'signup_identifier': 'test@example.com',
            'secret_code': '123456',
            'company_id': 1,
            'note': 'Demande de compte mobile.',
        },
        'note': 'Crée une demande de compte. Le compte doit ensuite être approuvé.',
    },
    {
        'group': 'Mobile Auth',
        'label': 'Password login dev',
        'route': '/api/acpec/mobile_auth/v1/password-login',
        'method': 'POST',
        'payload': {
            'identifier': 'test@example.com',
            'secret_code': '123456',
            'device_uid': 'dev-browser',
            'device_name': 'Console test',
            'platform': 'web',
            'app_version': 'dev',
        },
        'note': 'Login de développement. Nécessite le paramètre acpec_mobile_auth.allow_password_login=True. Retourne access_token et refresh_token.',
    },
    {
        'group': 'Mobile Auth',
        'label': 'Login alias compatible',
        'route': '/api/acpec/mobile_auth/v1/login',
        'method': 'POST',
        'payload': {
            'identifier': 'test@example.com',
            'secret_code': '123456',
            'device_uid': 'dev-browser',
            'device_name': 'Console test',
            'platform': 'web',
            'app_version': 'dev',
        },
        'note': 'Alias propre de /password-login, gardé pour compatibilité Flutter. Même réponse tokenisée, pas de dépendance au cookie session_id.',
    },
    {
        'group': 'Mobile Auth OTP',
        'label': 'Request OTP',
        'route': '/api/acpec/mobile_auth/v1/request-otp',
        'method': 'POST',
        'payload': {
            'identifier': 'test@example.com',
            'purpose': 'login',
        },
        'note': 'Demande un OTP. En dev, activer acpec_mobile_auth.otp_dev_mode=True pour recevoir dev_otp_code dans la réponse.',
    },
    {
        'group': 'Mobile Auth OTP',
        'label': 'Verify OTP',
        'route': '/api/acpec/mobile_auth/v1/verify-otp',
        'method': 'POST',
        'payload': {
            'identifier': 'test@example.com',
            'code': '000000',
            'device_uid': 'dev-browser',
            'device_name': 'Console test',
            'platform': 'web',
            'app_version': 'dev',
        },
        'note': 'Valide l’OTP et retourne une session mobile tokenisée. Remplacer code par le vrai OTP.',
    },
    {
        'group': 'Mobile Auth',
        'label': 'Me',
        'route': '/api/acpec/mobile_auth/v1/me',
        'method': 'POST',
        'payload': {},
        'requires_token': True,
        'note': 'Nécessite Authorization: Bearer access_token. La console ajoute automatiquement le token après login/OTP.',
    },
    {
        'group': 'Mobile Auth',
        'label': 'Session check',
        'route': '/api/acpec/mobile_auth/v1/session-check',
        'method': 'POST',
        'payload': {},
        'requires_token': True,
        'note': 'Vérifie la session mobile tokenisée courante.',
    },
    {
        'group': 'Mobile Auth',
        'label': 'Refresh',
        'route': '/api/acpec/mobile_auth/v1/refresh',
        'method': 'POST',
        'payload': {},
        'uses_refresh_token': True,
        'note': 'Renouvelle access_token et refresh_token. La console envoie automatiquement X-ACPEC-Refresh-Token si disponible.',
    },
    {
        'group': 'Mobile Auth',
        'label': 'Logout',
        'route': '/api/acpec/mobile_auth/v1/logout',
        'method': 'POST',
        'payload': {},
        'requires_token': True,
        'note': 'Révoque la session mobile courante.',
    },
    {
        'group': 'Mobile Auth Admin',
        'label': 'List account requests',
        'route': '/api/acpec/mobile_auth/v1/admin/account-requests',
        'method': 'POST',
        'payload': {
            'state': 'pending',
            'limit': 20,
            'offset': 0,
        },
        'requires_token': True,
        'note': 'Nécessite un token administrateur mobile ou une session web admin.',
    },
    {
        'group': 'Mobile Auth Admin',
        'label': 'Approve account request',
        'route': '/api/acpec/mobile_auth/v1/admin/account-requests/1/approve',
        'method': 'POST',
        'payload': {},
        'requires_token': True,
        'note': 'Remplacer 1 dans l’URL par l’ID réel de la demande.',
    },
    {
        'group': 'Mobile Auth Admin',
        'label': 'Reject account request',
        'route': '/api/acpec/mobile_auth/v1/admin/account-requests/1/reject',
        'method': 'POST',
        'payload': {
            'reason': 'Dossier incomplet.',
        },
        'requires_token': True,
        'note': 'Remplacer 1 dans l’URL par l’ID réel de la demande.',
    },
]
