{
    'name': 'ACPEC FuelToken Company Accounts',
    'version': '19.0.1.4.11',
    'category': 'ACPEC/FuelToken',
    'summary': 'Comptes Sociétés Tickets Carburant pour le back-office ACPEC',
    'author': 'ACPEC SARL',
    'website': 'https://acpec.odoorim.com',
    'license': 'OPL-1',
    'depends': [
        'mail',
        'portal',
        'acpec_mobile_auth',
        'acpec_fueltoken_base',
        'acpec_fueltoken_core',
        'acpec_fueltoken_purchase',
        'acpec_fueltoken_backoffice_ui',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/fueltoken_company_rules.xml',
        'views/company_distribution_wizard_views.xml',
        'views/fuel_distributor_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
